### PR TITLE
Javacc4 config input file

### PR DESCRIPTION
**Pull request by Henne**
This patchset applies the code from Configuration.java to the input file config.jj which is used to generate a fresh parser.
**Only config.jj is changed** in this patchset, so **nothing can break**.

A generated parser by JavaCC V4.0 from this config.jj has still differences to the currently used code,
but they are either trivial or unmodifiable by editing config.jj.

This is the diffstat of a patch from the current Configuration.java to a fresh one from JavaCC 4.0:

Configuration.java |   95 +++++++++++++++++++++--------------------------------
 1 file changed, 38 insertions(+), 57 deletions(-)

Best regards.

P.S.: I fully understand and agree with your arguments and I'm not discouraged by your rejection.
Also I understand that my initial pull request [#248](https://github.com/tlaplus/tlaplus/pull/248) was too ambitious and could have been made more comprehensible.

Sadly I could not reproduce the failed JUnit-Tests you mentioned in [#254](https://github.com/tlaplus/tlaplus/pull/254#issuecomment-473422610), since I ran them also on my machine where they did not fail. I'm using:
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

### CODE REVIEW

**Comment by lemmy** [comment]
@Henne Would you be interested in finishing the [Toolbox's unicode](https://github.com/tlaplus/tlaplus/tree/pron-unicode) feature?

**Comment by Henne** [comment]
It is not my topic of interest, but I think I see what you mean.
To take a look at that I need maven verify run cleanly on master, which is not the case at the moment.
I'll write a ticket on that.

**Comment by lemmy** [comment]
What is your area of interest?

**Comment by lemmy** [comment]
Would the issues (especially support for "\"" and "\\" in SANY) discussed in https://github.com/tlaplus/tlaplus/issues/159#issuecomment-481849812 match your area of interest?

**Comment by lemmy** [comment]
https://github.com/tlaplus/tlaplus/issues/408 would be a good reason to continue work on this PR.

**Comment by ahelwer** [comment]
Upon investigation the entire purpose of this parser is just to parse a large string encoding all the operator symbols of TLA+ and their precedence ranges, associativity, etc. during SANY initialization. It does not have anything to do with parsing the TLC configuration file as I originally believed (I actually independently created nearly this exact changeset because I didn't know about this PR). It is my opinion that this entire configuration parser should be torn out in favor of just defining a series of Operator objects directly, and therefore this PR should be closed. Ref #891

**Comment by lemmy** [comment]
This seems outdated.  @ahelwer please confirm.

**Comment by ahelwer** [comment]
It is outdated, yes. The config.jj file and its associated generated parser code is slated for deletion once I improve UT coverage of the remaining parts of it that are still used.

**Pull request closed without merging**
