### PR TITLE
Having fun with pr.yml

### PR DESCRIPTION
**Pull request by lemmy**
See main.yml.

[Build]

### CODE REVIEW

**Comment by ahelwer** [comment]
See #968 to fix grammar sync check

**Comment by lemmy** [comment]
https://github.com/tlaplus/tlaplus/actions/runs/9616849140/job/26527300098?pr=967

```
no changes added to commit (use "git add" and/or "git commit -a")
diff_count=$(git status --porcelain=v1 2>/dev/null | wc -l): D:\a\_temp\9e1aac39-ee4e-489d-99ba-e851cf876bcf.ps1:4
Line |
   4 |  diff_count=$(git status --porcelain=v1 2>/dev/null | wc -l)
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The term 'diff_count=$(git status --porcelain=v1 2>/dev/null | wc -l)' is not recognized as a name of a cmdlet,
     | function, script file, or executable program. Check the spelling of the name, or if a path was included, verify
     | that the path is correct and try again.
Error: Process completed with exit code 1.
```

https://github.com/tlaplus/tlaplus/blob/e17d73066ec53e155b5f44048cb41aa3eaa6587e/.github/workflows/pr.yml#L26-L28

**Comment by ahelwer** [comment]
As someone who has spent a lot (a *lot*) of hours dealing with the bad github CI development loop, I understand how frustrated you are with it. However, I don't believe that means we should just delete the things that are giving you trouble.

**Comment by lemmy** [comment]
Dropped unsuccessful attempts (commits) to run `pr.yml` on Windows because of the following two blockers:

https://github.com/tlaplus/tlaplus/issues/970
https://github.com/tlaplus/tlaplus/issues/943#issuecomment-2183255578

**Pull request merged**
