### PR TITLE
Add TLC command-line build instructions

### PR DESCRIPTION
**Pull request by thesammiller**
Provides general instructions for building TLC without the Toolbox, using ant on the command line.

Based on the conversation in https://github.com/tlaplus/tlaplus/issues/790, I'm adding to `CONTRIBUTING.md`. I'm keeping the instructions short to address the need of having these commands somewhere. Would a longer version be helpful? Would there be a better file to put it in?

The `ide` instructions mention OpenJDK 14, but this approach was tested and confirmed working with OpenJDK 11. Please let me know if that should be updated to 14.

Directions thanks to @lemmy and @Calvin-L. 

Thank you!

### CODE REVIEW

**Comment by thesammiller** [comment]
Looks like some of this information is in [the internal developer documentation] (https://github.com/tlaplus/tlaplus/blob/master/DEVELOPING.md ).

Not sure how this document compares/relates to `DEVELOPING.md`, but should maybe add a link to `DEVELOPING.md` in `CONTRIBUTING.md`. It didn't occur to me until reading the changes in https://github.com/tlaplus/tlaplus/pull/782

**Comment by lemmy** [comment]
It's probably good if the new and the old `DEVELOPING.md` are consolidated into a single document that is more easily discoverable by future contributors.

**Comment by thesammiller** [comment]
Added a commit to address the comment by @lemmy. IDE instructions for setting up in Intellij are still forthcoming and could be added to this PR or in a new one.

**Comment by Calvin-L** [comment]
Thanks for doing this. :)

**Pull request merged**
