### PR TITLE
Move JavaCC files to tla2sany.parser module

### PR DESCRIPTION
**Pull request by ahelwer**
This moves all the JavaCC files next to where they are actually used. The Ant build file has been modified to account for this. I also wrote a preamble to the README file explaining the general layout and development methods of the syntax parser.

No source code is modified in these changes so they cannot introduce any bugs.

### CODE REVIEW

**Review by Calvin-L — CHANGES_REQUESTED** [review]
We shouldn't move things into `src/` if we can help it. All non-java files in that folder are included in the distribution jar, meaning that after this change the distribution would include the javacc zip file and documentation. Not ideal!

Java projects canonically sort files by _type_ rather than _function_ (ref [Maven](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html), [Gradle](https://docs.gradle.org/current/userguide/organizing_gradle_projects.html)), which can be awkward for humans but is great for build systems: "Everything here goes through javac, everything here gets copied, everything here gets run as a test, etc." See also #848, which we reverted but I always meant to revisit.

I could imagine renaming the `javacc/README/` folder to `lib/javacc/` (to live with its corresponding binary distribution) and adding a new `README.md` to the `javacc/` folder, but I wouldn't go further than that.

**Comment by ahelwer** [comment]
Alas, the great dream is dead. How about things like READMEs? Where do you think those should go?

**Comment by ahelwer** [comment]
cc @lemmy for more input on where to put READMEs, I would like to sprinkle some README files throughout the source tree to give a general overview of development tactics for that area of the codebase. Does this seem like a good idea? Where should the docs go if that is not a good place for them?

**Comment by lemmy** [comment]
I don't mind having `README.md` files in Java source folders, as that's where people typically look for documentation. During the build process, the `.md` files can be excluded from the final JAR by configuring the filtering rules in the `customBuild.xml`.  That said, I would recommend using `package-info.java` instead. It is more compatible with Java build systems and offers better integration with IDEs.

**Pull request closed without merging**
