### PR TITLE
<fix> fix javvcc generator error

### PR DESCRIPTION
**Pull request by fwhdzh**
Hi, I find that when I compiles tlatools.jar, the javacc will report some errors due to a missing configuration of UTF_8 charset. 

TLC generate UTF-8-1

I see there are some other issues about the charset in javacc, like #919 . However, unlike that issue, this commit is simple and I hope it can prevent some compilering confusions for a short time to come.

By the way, I also found a small mistake on DEVELOPING.md. The link to tlaplus repository is not right. I also update it.

### CODE REVIEW

**Comment by ahelwer** [comment]
Oh wonderful, thanks! I thought I would have to upgrade to a newer version of JavaCC to fix this. Now it probably builds on windows.

**Comment by ahelwer** [comment]
Also DEVELOPING.md is being rewritten in https://github.com/tlaplus/tlaplus/issues/938, so if you'd like to revert the changes to that file in this PR and take a look at those it would be appreciated!

**Comment by ahelwer** [comment]
Another thing you will have to do to pass the continuous integration is sign these commits with a Developer Certificate of Origin. It is just a legal formality that says you yourself wrote this code and didn't take it from a proprietary project or something. The github CI result should give you a link telling you how to do that with a rebase command.

**Review by lemmy — APPROVED** [review]
LGTM

**Comment by fwhdzh** [comment]
> Oh wonderful, thanks! I thought I would have to upgrade to a newer version of JavaCC to fix this. Now it probably builds on windows. You can even check that with another modification in this PR, if you want! Add another commit to replace [this line](https://github.com/tlaplus/tlaplus/blob/c9dadac3569a9752c29ab027a86cfe817b573a0a/.github/workflows/pr.yml#L7) of PR.yml with the text:
> 
> ```yaml
> runs-on: ${{ matrix.os }}
> strategy:
>   matrix:
>     include: [ubuntu-latest, windows-latest]
> ```

Thank you. I have added this to the pr.yml.

**Comment by fwhdzh** [comment]
> Another thing you will have to do to pass the continuous integration is sign these commits with a Developer Certificate of Origin. It is just a legal formality that says you yourself wrote this code and didn't take it from a proprietary project or something. The github CI result should give you a link telling you how to do that with a rebase command.

I have read the document in #938. However, I find the document contains much more contents besides what this issue concerns. I think it would be better to use a standlone issue for that document update, like #938. What do you think?

**Review by lemmy — APPROVED** [review]

**Comment by lemmy** [comment]
@fwhdzh Thanks, I amended the commit messages and integrated your three commits into master

**Pull request closed without merging**
