### PR TITLE
Add new JLine dependencies

### PR DESCRIPTION
**Pull request by pera**
This PR relates to https://github.com/tlaplus/tlaplus/pull/862

In JLine 3.25.0 there are two extra dependencies:
* jline-builtins
* jline-console

Signature/hashes of the included artifacts:
https://repo1.maven.org/maven2/org/jline/jline-builtins/3.25.0/
https://repo1.maven.org/maven2/org/jline/jline-console/3.25.0/

I am opening this as a draft because there are currently 4 test cases that for some reason are not passing on my machine (not sure if my dev environment is setup correctly though):

```
-------------------------------------------------------------------------------
Test set: org.lamport.tla.toolbox.tool.tlc.output.data.TLCErrorTest
-------------------------------------------------------------------------------
Tests run: 8, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 0.004 s <<< FAILURE! - in org.lamport.tla.toolbox.tool.tlc.output.data.TLCErrorTest
testXA(org.lamport.tla.toolbox.tool.tlc.output.data.TLCErrorTest)  Time elapsed: 0.002 s  <<< FAILURE!
java.lang.AssertionError: expected:<2> but was:<1>
        at org.lamport.tla.toolbox.tool.tlc.output.data.TLCErrorTest.testX(TLCErrorTest.java:191)
        at org.lamport.tla.toolbox.tool.tlc.output.data.TLCErrorTest.testXA(TLCErrorTest.java:136)

testXB(org.lamport.tla.toolbox.tool.tlc.output.data.TLCErrorTest)  Time elapsed: 0 s  <<< FAILURE!
java.lang.AssertionError: expected:<2> but was:<1>
        at org.lamport.tla.toolbox.tool.tlc.output.data.TLCErrorTest.testX(TLCErrorTest.java:191)
        at org.lamport.tla.toolbox.tool.tlc.output.data.TLCErrorTest.testXB(TLCErrorTest.java:140)

testXC(org.lamport.tla.toolbox.tool.tlc.output.data.TLCErrorTest)  Time elapsed: 0 s  <<< FAILURE!
java.lang.AssertionError: expected:<2> but was:<1>
        at org.lamport.tla.toolbox.tool.tlc.output.data.TLCErrorTest.testX(TLCErrorTest.java:191)
        at org.lamport.tla.toolbox.tool.tlc.output.data.TLCErrorTest.testXC(TLCErrorTest.java:144)

testXD(org.lamport.tla.toolbox.tool.tlc.output.data.TLCErrorTest)  Time elapsed: 0 s  <<< FAILURE!
java.lang.AssertionError: expected:<2> but was:<1>
        at org.lamport.tla.toolbox.tool.tlc.output.data.TLCErrorTest.testX(TLCErrorTest.java:191)
        at org.lamport.tla.toolbox.tool.tlc.output.data.TLCErrorTest.testXD(TLCErrorTest.java:148)

testA(org.lamport.tla.toolbox.tool.tlc.output.data.TLCErrorTest)  Time elapsed: 0 s
testB(org.lamport.tla.toolbox.tool.tlc.output.data.TLCErrorTest)  Time elapsed: 0.001 s
testC(org.lamport.tla.toolbox.tool.tlc.output.data.TLCErrorTest)  Time elapsed: 0 s
testD(org.lamport.tla.toolbox.tool.tlc.output.data.TLCErrorTest)  Time elapsed: 0 s
```
These tests are in:
`tlaplus/toolbox/org.lamport.tla.toolbox.tool.tlc.ui.test/src/org/lamport/tla/toolbox/tool/tlc/output/data/TLCErrorTest.java`

@lemmy any ideas?

### CODE REVIEW

**Comment by lemmy** [comment]
`TLCErrorTest` seems unrelated.

**Comment by pera** [comment]
Yeah it looks unrelated: I get the same error when running the tests in the commit before mine (63e2a4c040fd476f651f3561e8fef842beaf74aa)

**Comment by lemmy** [comment]
You also need to include the definition of `${{ matrix.MVN_COMMAND }}` at the top of main.yml.

**Comment by pera** [comment]
Thanks, missed that variable

**Pull request merged**
