### PR TITLE
Sonar code improvements

### PR DESCRIPTION
**Pull request by indegro**
Improvements based on sonar:
Package - tlc2.util.

1. Added @ Override
2. Reordered the modifiers to compy with JLS
3. Replaced StringBuffer with StringBuilder (no ref escape, equivalent behaviour)

### CODE REVIEW

**Comment by lemmy** [comment]
Where is this going?  You can probably spend your time on more interesting issues.

**Comment by indegro** [comment]
Hello, 

I've decided to read code and try to understand it and meanwhile do some little improvements.
If there is some minor issues that I make take, just let me know

**Comment by indegro** [comment]
At the moment I have an idea to add `edit` support for TLA+ spec into IntelliJ Idea, cause it is the main IDE that I use at work.

**Comment by lemmy** [comment]
I would assume that adding editing support to IntelliJ is the opposite of a minor issue.

https://github.com/tlaplus/tlaplus/issues/321 is well defined and enclosed from my perspective.

**Comment by indegro** [comment]
Thanks, let me check what I can do there

**Comment by lemmy** [comment]
This has unfortunately become stale.

**Pull request closed without merging**
